lista = ('Atlético-PR','Bahia','Fortaleza','Internacional','Palmeiras','Flamengo','Santos','Vasco da Gama','Botafogo','Corinthians','Fluminense','Cruzeiro','São Paulo','Grêmio','América-MG','Athletico-PR','Red Bull Bragantino','Goiás','Atlético-MG','Cuiabá')
print('-='*60)
print(f'os 5 primiros colocados da lista são{lista[0:6]}')
print('-='*60)
print(f'os ultimos 4 colocados são{lista[-4:]}')
print('-='*120)
print(f'Em ordem alfabética{sorted(lista)}')
print('-='*60)
print(f'O Corinthians está na {lista.index("Corinthians")+1}ºposição')
